### ISSUE TITLE
Launch at Login not working

### ISSUE THREAD

**Issue by justatechie** [AngryKiller/iTunes-Discord#17]
Application does not auto-launch at login.

**Comment by AngryKiller** [comment]
I'm gonna check this later, in the mean time, if you are on macOS you can build the application and add it manually in the Users preference pane:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/16365421/116401403-8007ff80-a82b-11eb-9dcf-e43e8795908f.png">

**Comment by justatechie** [comment]
Attempted to build the application but was greeted with this error log:

`Error: Unresolved node modules: bufferutil, utf-8-validate
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/packageDependencies.ts:112:21
From previous event:
    at Collector.resolveUnresolvedHoisted (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/packageDependencies.ts:88:81)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/packageDependencies.ts:83:18
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Collector.collect (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/packageDependencies.ts:76:28)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/packageDependencies.ts:47:44
    at Generator.next (<anonymous>)
    at _getProductionDependencies (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/packageDependencies.js:92:37)
    at getProductionDependencies (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/packageDependencies.js:83:37)
    at Lazy.<anonymous> (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:138:24)
    at Generator.next (<anonymous>)
    at Lazy.get value [as value] (/Users/louie/iTunes-Discord/node_modules/lazy-val/src/main.ts:18:25)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/yarn.js:166:90
From previous event:
    at _getProductionDependencies (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/packageDependencies.js:92:37)
    at getProductionDependencies (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/packageDependencies.js:83:37)
    at Lazy.<anonymous> (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:138:24)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (/Users/louie/iTunes-Discord/node_modules/lazy-val/src/main.ts:18:25)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/yarn.js:166:90
    at Generator.next (<anonymous>)
From previous event:
    at _rebuild (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/yarn.ts:179:5)
    at rebuild (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/yarn.js:163:19)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/yarn.ts:20:11
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at _installOrRebuild (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/yarn.js:71:28)
    at installOrRebuild (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/yarn.js:55:28)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:509:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:470:70)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:420:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/louie/iTunes-Discord/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:136:16
    at /Users/louie/iTunes-Discord/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/louie/iTunes-Discord/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqCallback.oncomplete (fs.js:171:23)
From previous event:
    at Packager._build (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Packager.build (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/louie/iTunes-Discord/node_modules/electron-builder/src/builder.ts:228:10)
    at /Users/louie/iTunes-Discord/node_modules/electron-builder/src/cli/cli.ts:49:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! itunes-discord@0.6.1 dist: `electron-builder -m -w`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the itunes-discord@0.6.1 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/louie/.npm/_logs/2021-04-29T02_12_05_757Z-debug.log`

Heres the log file:
[2021-04-29T02_12_05_757Z-debug.log](https://github.com/AngryKiller/iTunes-Discord/files/6395913/2021-04-29T02_12_05_757Z-debug.log)

**Comment by AngryKiller** [comment]
Alright, so launch at login requires you to run the packaged app and not running it from the command line, so it's probably why it doesn't work. I'm gonna try to build it to see what happens, but from the log it looks like you are missing some npm packages, try running npm install with the --save-dev parameter.

**Comment by AngryKiller** [comment]
I can confirm it does build successfully for me. Did you run 'npm run pack-mac' to build it

**Comment by justatechie** [comment]
Sorry for the delay!

I've now run what you asked, but I got more errors:

`louie@Louies-MacBook-Pro iTunes-Discord % npm run pack-mac         

> itunes-discord@0.6.1 pack-mac /Users/louie/iTunes-Discord
> electron-builder -m --dir
  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
Error: Unresolved node modules: bufferutil, utf-8-validate
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/packageDependencies.ts:112:21
From previous event:
    at Collector.resolveUnresolvedHoisted (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/packageDependencies.ts:88:81)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/packageDependencies.ts:83:18
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Collector.collect (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/packageDependencies.ts:76:28)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/packageDependencies.ts:47:44
    at Generator.next (<anonymous>)
    at _getProductionDependencies (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/packageDependencies.js:92:37)
    at getProductionDependencies (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/packageDependencies.js:83:37)
    at Lazy.<anonymous> (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:138:24)
    at Generator.next (<anonymous>)
    at Lazy.get value [as value] (/Users/louie/iTunes-Discord/node_modules/lazy-val/src/main.ts:18:25)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/yarn.js:166:90
From previous event:
    at _getProductionDependencies (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/packageDependencies.js:92:37)
    at getProductionDependencies (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/packageDependencies.js:83:37)
    at Lazy.<anonymous> (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:138:24)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (/Users/louie/iTunes-Discord/node_modules/lazy-val/src/main.ts:18:25)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/yarn.js:166:90
    at Generator.next (<anonymous>)
From previous event:
    at _rebuild (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/yarn.ts:179:5)
    at rebuild (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/yarn.js:163:19)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/util/yarn.ts:20:11
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at _installOrRebuild (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/yarn.js:71:28)
    at installOrRebuild (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/out/util/yarn.js:55:28)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:509:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:470:70)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:420:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/louie/iTunes-Discord/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:136:16
    at /Users/louie/iTunes-Discord/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/louie/iTunes-Discord/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqCallback.oncomplete (fs.js:171:23)
From previous event:
    at Packager._build (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Packager.build (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/louie/iTunes-Discord/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/louie/iTunes-Discord/node_modules/electron-builder/src/builder.ts:228:10)
    at /Users/louie/iTunes-Discord/node_modules/electron-builder/src/cli/cli.ts:49:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! itunes-discord@0.6.1 pack-mac: `electron-builder -m --dir`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the itunes-discord@0.6.1 pack-mac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/louie/.npm/_logs/2021-05-10T09_09_17_245Z-debug.log`

I ran with the --save-dev parameter, still got an error, I re-ran `npm i electron-builder -G` and then ran `npm run pack-mac  ` but got the error you see above.

**Comment by AngryKiller** [comment]
What happens if you try to install the 2 packages the error says are not present? bufferutil and utf-8-validate.

**Comment by justatechie** [comment]
right so we get passed the error. But now we have this new issue:


`• electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • rebuilding native production dependencies platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=5.0.5 appOutDir=dist/mac
  • skipped macOS application code signing reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=`
`0 identities found`
`Valid identities only`
`0 valid identities found`

**Comment by justatechie** [comment]
actually never mind, it did built it. just skipped the signing. Perfect thank you! (Probably should add these two packages to the initial install phase.)
