### ISSUE TITLE
(node:8003) UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by https-finesse** [AngryKiller/iTunes-Discord#6]
I followed every step you mentioned.

I noticed i got some issues while running **`npm run dist`** which lead to this error:

```
• electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • rebuilding native production dependencies platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=5.0.13 appOutDir=dist/mac
  • signing         file=dist/mac/iTunes⇄Discord.app identityName=Apple Development: simonextoscano@gmail.com (LXE38YCVY5) identityHash=76A0FC4D82F133630828E10083C608EF464A130A provisioningProfile=none
  • building        target=macOS zip arch=x64 file=dist/iTunes⇄Discord-0.6.1-mac.zip
  • building        target=DMG arch=x64 file=dist/iTunes⇄Discord-0.6.1.dmg
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=5.0.13 appOutDir=dist/win-unpacked
  ⨯ error: fork/exec /Users/simone/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine: bad CPU type in executable
path: /Users/simone/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine
args: /Users/simone/Library/Caches/electron-builder/wine/wine-2.0.3-mac-10.13/bin/wine /Users/simone/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.4.0/rcedit-ia32.exe /Users/simone/Documents/GitHub/iTunes-Discord/dist/win-unpacked/iTunes⇄Discord.exe --set-version-string FileDescription iTunes⇄Discord --set-version-string ProductName iTunes⇄Discord --set-version-string LegalCopyright Copyright © 2018-2019 AngryKiller --set-file-version 0.6.1 --set-product-version 0.6.1.0 --set-version-string InternalName iTunes⇄Discord --set-version-string OriginalFilename  --set-version-string CompanyName AngryKiller --set-icon /Users/simone/Documents/GitHub/iTunes-Discord/dist/.icon-ico/icon.ico



0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dist' ]
2 info using npm@6.13.7
3 info using node@v10.15.1
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle itunes-discord@0.6.1~predist: itunes-discord@0.6.1
6 info lifecycle itunes-discord@0.6.1~dist: itunes-discord@0.6.1
7 verbose lifecycle itunes-discord@0.6.1~dist: unsafe-perm in lifecycle true
8 verbose lifecycle itunes-discord@0.6.1~dist: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/simone/Documents/GitHub/iTunes-Discord/node_modules/.bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle itunes-discord@0.6.1~dist: CWD: /Users/simone/Documents/GitHub/iTunes-Discord
10 silly lifecycle itunes-discord@0.6.1~dist: Args: [ '-c', 'electron-builder -m -w' ]
11 silly lifecycle itunes-discord@0.6.1~dist: Returned: code: 1  signal: null
12 info lifecycle itunes-discord@0.6.1~dist: Failed to exec dist script
13 verbose stack Error: itunes-discord@0.6.1 dist: `electron-builder -m -w`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid itunes-discord@0.6.1
15 verbose cwd /Users/simone/Documents/GitHub/iTunes-Discord
16 verbose Darwin 19.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dist"
18 verbose node v10.15.1
19 verbose npm  v6.13.7
20 error code ELIFECYCLE
21 error errno 1
22 error itunes-discord@0.6.1 dist: `electron-builder -m -w`
22 error Exit status 1
23 error Failed at the itunes-discord@0.6.1 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

Every other step is successful.

But then when I **`npm start`** it instantly crashes:

```
> itunes-discord@0.6.1 start /Users/simone/Documents/GitHub/iTunes-Discord
> electron .

settings.js loaded
Tray added in the status bar!
iTunes is not longer playing!
Tray information updated!
Disconnected from rpc!
(node:8003) UnhandledPromiseRejectionWarning: Error: connection closed
    at /Users/simone/Documents/GitHub/iTunes-Discord/node_modules/discord-rpc/src/client.js:107:20
    at Map.forEach (<anonymous>)
    at IPCTransport.<anonymous> (/Users/simone/Documents/GitHub/iTunes-Discord/node_modules/discord-rpc/src/client.js:106:25)
    at Object.onceWrapper (events.js:282:20)
    at IPCTransport.emit (events.js:194:13)
    at /Users/simone/Documents/GitHub/iTunes-Discord/node_modules/discord-rpc/src/transports/ipc.js:137:18
    at decode (/Users/simone/Documents/GitHub/iTunes-Discord/node_modules/discord-rpc/src/transports/ipc.js:92:5)
    at Socket.<anonymous> (/Users/simone/Documents/GitHub/iTunes-Discord/node_modules/discord-rpc/src/transports/ipc.js:120:7)
    at Socket.emit (events.js:194:13)
    at emitReadable_ (_stream_readable.js:551:12)
(node:8003) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8003) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8003) UnhandledPromiseRejectionWarning: Error: connection closed
    at /Users/simone/Documents/GitHub/iTunes-Discord/node_modules/discord-rpc/src/client.js:107:20
    at Map.forEach (<anonymous>)
    at IPCTransport.<anonymous> (/Users/simone/Documents/GitHub/iTunes-Discord/node_modules/discord-rpc/src/client.js:106:25)
    at Object.onceWrapper (events.js:282:20)
    at IPCTransport.emit (events.js:194:13)
    at /Users/simone/Documents/GitHub/iTunes-Discord/node_modules/discord-rpc/src/transports/ipc.js:137:18
    at decode (/Users/simone/Documents/GitHub/iTunes-Discord/node_modules/discord-rpc/src/transports/ipc.js:92:5)
    at Socket.<anonymous> (/Users/simone/Documents/GitHub/iTunes-Discord/node_modules/discord-rpc/src/transports/ipc.js:120:7)
    at Socket.emit (events.js:194:13)
    at emitReadable_ (_stream_readable.js:551:12)
(node:8003) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Please let me know if it's an issue related on my end, if it is: how can I solve this? Thanks

**Comment by AngryKiller** [comment]
Hello,

For the first error, I guess you are running macOS Catalina, which doesn't run 32bit code anymore, since the error is related to wine not being able to run (bad CPU type in executable), and I'm not having this error on Mojave, but it shouldn't be a problem for you since this is only useful for building the Windows version of iTunes-Discord.

However, for the second one, I didn't use iTunes-Discord for a long time, and now that I try to run it, I'm getting the same error as you, so I'm currently investigating on it and will try to push a fix as soon as possible.

**Comment by https-finesse** [comment]
Thank you, appreciate it! have a great work.

**Comment by AngryKiller** [comment]
You may still have an issue if you are running Catalina with the Music app related to https://github.com/AngryKiller/iTunes-bridge not supporting it, which I am currently fixing too.
